server:
  port: 2001    #端口号
spring:
  application:
    name: eureka-server01 # 应用名称，会在Eureka中作为服务的id标识（serviceId）
    #profiles:
    #active: dev
eureka:
  instance:
    hostname: eureka-server01
  server:
    enable-self-preservation: false #关闭自我保护机制
  client:
    register-with-eureka: false   #是否将自己注册到Eureka中
    fetch-registry: false   #是否从eureka中获取服务信息
    service-url:
      defaultZone: http://eureka-server02:2002/eureka/,http://eureka-server03:2003/eureka/ # 集群 EurekaServer的地址  搭集群就是eureka相互注册，并且配置另外eurek地址
