server:
  port: 2003    #端口号
spring:
  application:
    name: eureka-server03 # 应用名称，会在Eureka中作为服务的id标识（serviceId）
    #profiles:
    #active: dev
eureka:
  instance:
    hostname: eureka-server03
  server:
    enable-self-preservation: false #关闭自我保护机制
  client:
    register-with-eureka: false   #是否将自己注册到Eureka中
    fetch-registry: false   #是否从eureka中获取服务信息
    service-url:
      defaultZone: http://eureka-server01:2001/eureka/,http://eureka-server02:2002/eureka/